#!/usr/bin/env python
# -*- coding: utf-8 -*-

alum_raw = """
1	Danny Janu	Danny Janu	<p>Put on his band uniform and hitchiked from Hamilton to the music centre for a performance in the Rememberance Day Parade.  Unfortunately, it was the parade in Hamilton we were doing that day and he missed it.</p>	1972	2007-05-13 12:00:00
2	Barfy	Barfy	<p>The band was staying in a hotel somewhere for a big parade, (probablyin the states.)  Somehow, his hotel room key ended up in the toilet afterit had been used, but before it had been flushed.  Rather than reach inand pick it out, this recipient erroneously believed that the weight ofthe key would make it too heavy to actually go down the bog so he flushedthe toilet believing that the bad stuff would go away, but the key wouldremain.  It didn't.</p>	1973	2007-05-13 12:00:00
3	Phil McArthur	Phil McArthur	<p>Dilligently hitchhiked to Kingston for a parade to catch up with the bandafter he had to work or just missed the bus or something.  He had a ride allthe way down the 401 when he spotted the equipment truck at the side of thehighway right about at the junction of the 115 that goes up to Peterborough.He had the driver drop him off so he could catch a ride the rest of the waywith Charlie, or whoever was driving the truck only to discover that the truckhad broken down and was abandoned there.  He started hitching again butbecause of the lost time, he didn't make it to Kingston on time.</p>	1974	2007-05-13 12:00:00
4	Dave Jacques	Dave Jacques	<p>Packed his passport in his uniform bag which was then loaded into the equipment truck headed for the airport in Europe(1975) . Having realized this, the equipment truck needed to be completely unpacked so he could get on the plane to come home.</p><p>Receiving "Honourable Mention" that year was Roy Russell. At a Hamilton Tiger Cats game, the band was performing at the half time show. During the idle time, with only 3 or 4 people on the bus, he sat on the driver's seat and decided to push on the pedals. When he pushed on the clutch, the bus started to roll backwards. He saw the two other buses, on either side of them "rolling forward", or so he thought! They stopped after the bus hit the building. The driver, who had a perfect safety record, up to that point in time, was pretty ticked off at him. So was Bob Webb.</p><p>Even though Roy didn't win the award that year, his legacy lives on. The next year, when the "Band Rules" were revised, there was a rule that said something along the lines of "No band member shall sit in the driver's seat of the bus". He was hoping that they would rename it to the "Russell clause".</p>	1975	2007-03-03 12:00:00
5	Carolyn Whiskin	Carolyn Whiskin	<p>Carolyn was in the position of Drum Major at that time.  While marching in the Calgary Stampede parade, Carolyn majestically, yet inadvertantly positioned her mace right into a sewer grate.  The band continued to march playing "Strike Up the Band" while Carolyn was frantically trying to pull the mace free.  As the clarinets passed by, she gave a final heave, broke the decorative chain and pulled her mace free.  She regained her position and her composure, and continued the rest of the parade, marching the "cane-walk" while constantly being whipped in the right leg with the newly-detached chain.</p><p>Congratulations on deserving this award.... and the sad thing was - I was not there to share in this event!<i>Submitted by Alan Whiskin (past Drum Major with and present husband of Carolyn)</i></p>	1982	2007-03-03 12:00:00
6	Steve (Animal) Gaul	Steve (Animal) Gaul	<p>Forgot his band shoes and was late (as usual) for the Dixieland gang, so hewent to the uniform room and grabbed the first pair of shoes that looked closeto his size as Phil Austin was yelling at him to get going.</p><p>When he arrived at the gig he had his shirt on and Phil asked him if the shoesfit. He wasn't sure and tried them on, putting them on first before his pants.Then Phil noticed they were on and once again urged Steve to get going.</p><p>With an instinct born of long years of band experience he grabbed his tunicand ran. When he got to the door and started to go out in public Philfortunately noticed that Steve in his haste had neglected to complete dressingand was sans pants.</p>	1988	2007-04-17 12:00:00
7	Julie Thompson	Julie Thompson	<p>At one of the ever-popular band dances, she decided to wear an ankle length short sleeved dress that buttoned up the front (top to bottom). She was sitting on one of the risers, when one of her favourite songs came on. She jumped up and yes, the dress popped open (top to bottom). It was quite the show.To this day, we never let her forget it.</p>	1992	2007-03-03 12:00:00
8	Mr. Garnier	Mr. Garnier	<p>The Band traveled to Toronto to perform our field show at a Toronto Blue Jaysgame, as we often did in those days (the Band played during both World Seriesand the 1991 All Star Game). We lined up in formation in the bowels of theSkydome near where our buses parked and marched in twos to down behind theoutfield wall by the visitor's bullpen. As we arrived our Marching DirectorMr. Garnier lined us up in such a way as to prepare us to go out onto thefield. At this moment I should have realized something was wrong as I wasset to lead the group rather then be at the end of it.</p><p>We didn't think too much of it until we were marching out and the realizationhit us that the two halves of the Band were going to be inverted with the lefton the right and the right on the left. Once set the Drum Major called out"Band, Are you ready!" to which no one thought to bring to their attention ourcurrent predicament and we reflexively yelled "Yes Sir". The cadence was givenand off we went. In spite of the looks of terror on the faces of some of theband the whole thing seemed to work, even the scatter which we thought atthe time would have us colliding into one another left and right. Once we gotoff the field we all couldn't help but discuss the fact we had just done ourfield show backwards in front of 50,000+ fans. For lining us up backwardsMr. Garnier was awarded that year's Wallace B. Wallace Award.</p>	1993	2007-03-08 12:00:00
9	Simon Matthews	Simon Matthews	<p>It was the Band picnic and it was a beautiful, warm summer's day atHidden Valley Park. During the game of capture the flag (members againststaff, boosters and parents) Drum Major Simon Matthews started making a breakfor it across the open field towards our head Chap Mrs. Webb.  Simon would runfor a moment, then stop and change direction a little, then run some more andchange direction again with Mrs. Webb staring him down all the while.</p><p>Finally he decided to run right at her hoping to get by. While Simon felt hismoves were good enough to pull it off, Mrs. Webb had other ideas. She held outher arm which closelined poor Simon and took him down like a tonne of bricks.It was truly a hilarious sight for all those who saw it and for it Simon wasawarded the 1995 Wallace B. Wallace Award.</p>	1995	2007-03-08 12:00:00
10	Shaun Woods	Shaun Woods	<p>For mooning Mr. Garnier and some chaperones by accident on our tour inBaltimore.</p>	1996	2007-03-03 12:00:00
11	Kevin Winterton	Kevin Winterton	<p>Fell asleep during a concert practice. Bill Hughes took notice and got thedrumline to surround him and wake him up.</p>	2001	2007-03-18 12:00:00
12	Chrissy Taylor	Chrissy Taylor	<p>Fell through a chair in the rehearsal hall while standing on it, resulting in a leg injury.</p>	2002	2007-03-03 12:00:00
13	Trevor Davies	Trevor Davies	<p>When in Miami for the Orange Bowl climbed up a palm tree to get me a coconut. He had a really hard time getting it down and eventually he fell out of the tree. To top it all off, while he was sitting on the ground after his fall, the coconut fell out of the tree and hit him in the head!</p>	2003	2007-03-03 12:00:00
14	Myles Tompkins	Myles Tompkins	<p>Set off fire works and fire crackers inside a Military Safe Zone in Courseulles-Sur-Mer(Juno Beach), France when there for the 60th anniversary of D-Day.</p>	2004	2007-03-03 12:00:00
15	Rob Bennett	Rob Bennett	<p><i>We know you won it during the 1999 Christmas Parade - and for what... `nuff said</i></p>	1999	2007-03-18 12:00:00
"""
alums = []
for row in alum_raw.split('\n'):
    fields = row.replace("'","\\'").split('\t')
    if len(fields) == 6:
        alums.append( "(%s,'%s','%s','%s',%s,'%s')" % (fields[0], fields[1],fields[2],fields[3],fields[4],fields[5]) )

print "%s;" % str(',\n'.join(alums))

